rrbot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Position Controllers ---------------------------------------
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_HipY_J1
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_HipR_J2
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint3_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_HipP_J3
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint4_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_KneeP_J4
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint5_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_AnkleP_J5
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint6_position_controller:
        type: effort_controllers/JointPositionController
        joint: RLeg_AnkleR_J6
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint7_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_HipY_J1
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint8_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_HipR_J2
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint9_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_HipP_J3
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint10_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_KneeP_J4
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint11_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_AnkleP_J5
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint12_position_controller:
        type: effort_controllers/JointPositionController
        joint: LLeg_AnkleR_J6
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint13_position_controller:
        type: effort_controllers/JointPositionController
        joint: Waist_Y_J1
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint14_position_controller:
        type: effort_controllers/JointPositionController
        joint: Waist_Y_J2
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint15_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_ShoulderP_J1
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint16_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_ShoulderR_J2
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint17_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_ShoulderY_J3
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint18_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_ElbowP_J4
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint19_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_WristY_J5
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint20_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_WristR_J6
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint21_position_controller:
        type: effort_controllers/JointPositionController
        joint: RArm_WristP_J7
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint22_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_ShoulderP_J1
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint23_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_ShoulderR_J2
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint24_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_ShoulderY_J3
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint25_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_ElbowP_J4
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint26_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_WristY_J5
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint27_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_WristR_J6
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
    joint28_position_controller:
        type: effort_controllers/JointPositionController
        joint: LArm_WristP_J7
        pid: {p: 10000.0, i: 10.0, d: 100.0}
        setpoint : 0
